version: '3'

services:

  web_server:
    build: .
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app/
    ports:
      - '${WEB_PORT}:443'
    depends_on:
      - db_server
    environment:
      - PHP_MEM_LIMIT=4048M
      - COMPOSER_MEMORY_LIMIT=4048M

  db_server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - '${DB_PORT}:3306'
